name: Keep awake

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Ping uuid service
        shell: bash
        run: curl -I https://uuid-364w.onrender.com
