name: Healthcheck

on:
  schedule:
    - cron: "*/12 * * * *"

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Ping uuid
        uses: 102/website-healthcheck@v1.0.1
        with:
          web-url: https://uuid-364w.onrender.com/
